var hierarchy =
[
    [ "AllocatedBuffer", "a00282.html", null ],
    [ "AllocatedImage", "a00314.html", null ],
    [ "catos::App", "a00130.html", null ],
    [ "catos::AppCreationInfo", "a00126.html", null ],
    [ "Bounds", "a00278.html", null ],
    [ "Camera", "a00178.html", null ],
    [ "ComponentTest", "a00374.html", null ],
    [ "ComputeEffect", "a00214.html", null ],
    [ "ComputePushConstants", "a00210.html", null ],
    [ "DeletionQueue", "a00310.html", null ],
    [ "DescriptorAllocator", "a00186.html", null ],
    [ "DescriptorAllocatorGrowable", "a00194.html", null ],
    [ "DescriptorLayoutBuilder", "a00182.html", null ],
    [ "DescriptorWriter", "a00202.html", null ],
    [ "DrawContext", "a00234.html", null ],
    [ "EngineStats", "a00274.html", null ],
    [ "catos::Entity", "a00386.html", null ],
    [ "Foo", "a00366.html", null ],
    [ "FrameData", "a00206.html", null ],
    [ "GeoSurface", "a00254.html", null ],
    [ "GLTFMaterial", "a00250.html", null ],
    [ "GLTFMetallic_roughness", "a00218.html", null ],
    [ "GPUDrawPushConstants", "a00298.html", null ],
    [ "GPUMeshBuffers", "a00290.html", null ],
    [ "GPUSceneData", "a00294.html", null ],
    [ "catos::HashFunc< K >", "a00338.html", null ],
    [ "catos::hashmap< K, V, F >", "a00342.html", null ],
    [ "catos::hashnode< K, V >", "a00334.html", null ],
    [ "IRenderable", "a00246.html", [
      [ "LoadedGLTF", "a00266.html", null ],
      [ "Node", "a00262.html", [
        [ "MeshNode", "a00238.html", null ]
      ] ]
    ] ],
    [ "catos::vector< T >::iterator", "a00362.html", null ],
    [ "catos::key_not_found", "a00330.html", null ],
    [ "GLTFMetallic_roughness::MaterialConstants", "a00222.html", null ],
    [ "MaterialInstance", "a00306.html", null ],
    [ "MaterialPipeline", "a00302.html", null ],
    [ "GLTFMetallic_roughness::MaterialResources", "a00226.html", null ],
    [ "MeshAsset", "a00258.html", null ],
    [ "catos::Method", "a00146.html", null ],
    [ "catos::MethodInvoker< ReturnType, ClassType, Args >", "a00142.html", null ],
    [ "catos::no_item_found", "a00326.html", null ],
    [ "out_of_range", "a00354.html", null ],
    [ "catos::Pair< K, V >", "a00346.html", null ],
    [ "catos::Pair< py::object *, catos::ScriptInfo >", "a00346.html", null ],
    [ "PipelineBuilder", "a00270.html", null ],
    [ "DescriptorAllocator::PoolSizeRatio", "a00190.html", null ],
    [ "DescriptorAllocatorGrowable::PoolSizeRatio", "a00198.html", null ],
    [ "catos::Property", "a00134.html", [
      [ "catos::PropertyImpl< T, U >", "a00138.html", null ]
    ] ],
    [ "catos::math::Quaternion", "a00174.html", null ],
    [ "catos::Registry", "a00154.html", null ],
    [ "RenderObject", "a00230.html", null ],
    [ "catos::Script", "a00378.html", null ],
    [ "catos::ScriptInfo", "a00318.html", null ],
    [ "catos::ScriptingEngine", "a00322.html", null ],
    [ "catos::string", "a00350.html", null ],
    [ "catos::Transform", "a00382.html", null ],
    [ "TransformComponent", "a00370.html", null ],
    [ "catos::TypeInfo", "a00150.html", null ],
    [ "catos::vector< T >", "a00358.html", null ],
    [ "catos::math::Vector2", "a00166.html", null ],
    [ "catos::math::Vector3", "a00170.html", null ],
    [ "catos::vector< catos::Entity * >", "a00358.html", null ],
    [ "catos::vector< catos::Pair< py::object *, catos::ScriptInfo > >", "a00358.html", null ],
    [ "Vertex", "a00286.html", null ],
    [ "VulkanEngine", "a00242.html", null ],
    [ "catos::Window", "a00162.html", null ],
    [ "catos::WindowCreationInfo", "a00158.html", null ],
    [ "catos::World", "a00390.html", null ]
];