var hierarchy =
[
    [ "AllocatedBuffer", "a00262.html", null ],
    [ "AllocatedImage", "a00294.html", null ],
    [ "catos::App", "a00118.html", null ],
    [ "catos::AppCreationInfo", "a00114.html", null ],
    [ "Bounds", "a00258.html", null ],
    [ "Camera", "a00158.html", null ],
    [ "catos::ComponentPool", "a00326.html", null ],
    [ "ComponentTest", "a00310.html", null ],
    [ "ComputeEffect", "a00194.html", null ],
    [ "ComputePushConstants", "a00190.html", null ],
    [ "DeletionQueue", "a00290.html", null ],
    [ "DescriptorAllocator", "a00166.html", null ],
    [ "DescriptorAllocatorGrowable", "a00174.html", null ],
    [ "DescriptorLayoutBuilder", "a00162.html", null ],
    [ "DescriptorWriter", "a00182.html", null ],
    [ "DrawContext", "a00214.html", null ],
    [ "EngineStats", "a00254.html", null ],
    [ "catos::EntityInfo", "a00322.html", null ],
    [ "Foo", "a00302.html", null ],
    [ "FrameData", "a00186.html", null ],
    [ "GeoSurface", "a00234.html", null ],
    [ "GLTFMaterial", "a00230.html", null ],
    [ "GLTFMetallic_roughness", "a00198.html", null ],
    [ "GPUDrawPushConstants", "a00278.html", null ],
    [ "GPUMeshBuffers", "a00270.html", null ],
    [ "GPUSceneData", "a00274.html", null ],
    [ "IRenderable", "a00226.html", [
      [ "LoadedGLTF", "a00246.html", null ],
      [ "Node", "a00242.html", [
        [ "MeshNode", "a00218.html", null ]
      ] ]
    ] ],
    [ "catos::Query< Components >::Iterator", "a00318.html", null ],
    [ "GLTFMetallic_roughness::MaterialConstants", "a00202.html", null ],
    [ "MaterialInstance", "a00286.html", null ],
    [ "MaterialPipeline", "a00282.html", null ],
    [ "GLTFMetallic_roughness::MaterialResources", "a00206.html", null ],
    [ "MeshAsset", "a00238.html", null ],
    [ "catos::Method", "a00134.html", null ],
    [ "catos::MethodInvoker< ReturnType, ClassType, Args >", "a00130.html", null ],
    [ "PipelineBuilder", "a00250.html", null ],
    [ "DescriptorAllocator::PoolSizeRatio", "a00170.html", null ],
    [ "DescriptorAllocatorGrowable::PoolSizeRatio", "a00178.html", null ],
    [ "catos::Property", "a00122.html", [
      [ "catos::PropertyImpl< T, U >", "a00126.html", null ]
    ] ],
    [ "catos::Query< Components >", "a00314.html", null ],
    [ "catos::Registry", "a00142.html", null ],
    [ "RenderObject", "a00210.html", null ],
    [ "STL::String", "a00298.html", null ],
    [ "TransformComponent", "a00306.html", null ],
    [ "catos::TypeInfo", "a00138.html", null ],
    [ "catos::math::Vector2", "a00154.html", null ],
    [ "Vertex", "a00266.html", null ],
    [ "VulkanEngine", "a00222.html", null ],
    [ "catos::Window", "a00150.html", null ],
    [ "catos::WindowCreationInfo", "a00146.html", null ],
    [ "catos::World", "a00330.html", null ]
];